/* eslint-disable react-hooks/rules-of-hooks */
import React from "react";
import Head from "next/head";
import Image from "next/image";
import Banner from "../../components/Banner";
import ourService from "../../public/ourServices.jpeg";
import thumbnail from "../../public/video.png";
import play from "../../public/playButton.png";
import Footer from "../../components/Footer";
import { useRouter } from "next/router";
import withAuth from "../../auth/withAuth";
const pid = () => {
  const router = useRouter();
  const { pid } = router.query;
  console.log(pid);
  return (
    <div>
      <Head>
        <title>Request service / Tadbeer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icon.ico" />
      </Head>
      <Banner
        imageSrc={ourService}
        imageUlt="Our Services banner"
        text1={pid}
        textPosition={
          "top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2"
        }
      />
      {pid === "Domestic workers Service Line" ? (
        <div className="flex flex-col md:m-20 m-10 md:space-y-5 space-y-1">
          <h1 className="lg:text-5xl md:text-2xl xs:text-sm text-[10px] text-[#E48100] font-lato font-extrabold">
            Domestic Workers Service Line
          </h1>
          <p className="md:text-lg xs:text-[10px] text-[7px]">
            Ministry of Human Resources and Emiratization has developed domestic
            workers services into several packages to serve the community with
            all different domestic workers’ needs as well as to facilitate the
            contracting process between domestic workers and employers.
          </p>
          <div className="md:space-y-10 space-y-5">
            <h3 className="md:text-lg xs:text-[10px] text-[7px]">
              The packages are:
            </h3>
            <div className="ml-5 space-y-3">
              <div className="flex items-start space-x-1 max-w-6xl">
                <span className="md:text-base text-xs">🔵</span>
                <h1 className="text-[#234F7E] md:text-base font-roboto xs:text-[8px] text-[5px]">
                  <span className="font-roboto font-bold md:text-lg text-xs">
                    Traditional Package:
                  </span>
                  <span className="md:text-base text-xs">
                    {" "}
                    Recruitment services for a domestic worker from in or
                    outside the country where the domestic worker is sponsored
                    by the employer and stays with them during the contract
                    period.
                  </span>
                </h1>
              </div>
              <div className="flex items-start space-x-1 max-w-6xl">
                <span className="md:text-base text-xs">🔵</span>
                <h1 className="text-[#234F7E] md:text-base font-roboto xs:text-[8px] text-[5px]">
                  <span className="font-roboto font-bold md:text-lg text-xs">
                    Temporary Package:
                  </span>
                  <span className="md:text-base text-xs">
                    {" "}
                    This service is providing a domestic worker sponsored by
                    Tadbeer service center to work for a contractual period.
                    After which the worker is or is not allowed to transfer as a
                    resident domestic worker sponsored by the employer if the
                    concerned parties agree.
                  </span>
                </h1>
              </div>
              <div className="flex items-start space-x-1 max-w-6xl">
                <span className="md:text-base text-xs">🔵</span>
                <h1 className="text-[#234F7E] md:text-base font-roboto xs:text-[8px] text-[5px]">
                  <span className="font-roboto font-bold md:text-lg text-xs">
                    Flexible Package:
                  </span>
                  <span className="md:text-base text-xs">
                    {" "}
                    Domestic worker sponsored by Tadbeer service center to work
                    on a flexible system (hours, days, week)
                  </span>
                </h1>
              </div>
            </div>
          </div>
        </div>
      ) : (
        <div className="flex flex-col md:m-20 m-10 md:space-y-10 space-y-1">
          <h1 className="lg:text-5xl md:text-2xl xs:text-sm text-[10px] text-[#E48100] font-lato font-extrabold">
            Clearance and Typing services
          </h1>
          <p className="md:text-lg xs:text-[10px] text-[7px]">
            All government typing services pertaining to the employment and
            entry visas of domestic and household workers, including but limited
            to the following:
          </p>
          <div className="ml-5 md:space-y-5 space-y-0">
            <h1 className="text-[#234F7E] md:text-base font-bold text-lg font-roboto xs:text-[8px] text-[5px] xs:h-5 h-4">
              🔵 Entry Permit
            </h1>
            <h1 className="text-[#234F7E] md:text-base font-bold text-lg font-roboto xs:text-[8px] text-[5px] xs:h-5 h-4">
              🔵 Change of Status
            </h1>
            <h1 className="text-[#234F7E] md:text-base font-bold text-lg font-roboto xs:text-[8px] text-[5px] xs:h-5 h-4">
              🔵 Emirates Identity / National ID
            </h1>
            <h1 className="text-[#234F7E] md:text-base font-bold text-lg font-roboto xs:text-[8px] text-[5px] xs:h-5 h-4">
              🔵 Government and Medical Insurance
            </h1>
            <h1 className="text-[#234F7E] md:text-base font-bold text-lg font-roboto xs:text-[8px] text-[5px] xs:h-5 h-4">
              🔵 Medical Test
            </h1>
            <h1 className="text-[#234F7E] md:text-base font-bold text-lg font-roboto xs:text-[8px] text-[5px] xs:h-5 h-4">
              🔵 Residency Visa Stamping Application
            </h1>
            <h1 className="text-[#234F7E] md:text-base font-bold text-lg font-roboto xs:text-[8px] text-[5px] xs:h-5 h-4">
              🔵 Domestic Worker Visa Renewal
            </h1>
            <h1 className="text-[#234F7E] md:text-base font-bold text-lg font-roboto xs:text-[8px] text-[5px] xs:h-5 h-4">
              🔵 Domestic Worker Visa Cancellation
            </h1>
          </div>
        </div>
      )}

      <div className="md:my-22 my-10 bg-[#E7EDF3] md:p-20 p-10">
        <form action="" method="post" className="max-w-xl mx-auto space-y-5">
          <h1 className="block md:text-4xl xs:text-xl text-sm text-center font-medium text-[#234F7E]">
            Service Request Form
          </h1>
          <div className="flex flex-col items-start space-y-3">
            <h1 className="text-[#234F7E] font-lato font-semibold text-lg">
              Service Name
            </h1>
            <h1 className="text-[#234F7E] md:text-2xl font-lato font-bold xs:text-lg text-sm">
              {pid}
            </h1>
          </div>
          <div className="relative z-0 w-full mb-6 group">
            <input
              type="text"
              className="block py-2.5 px-0 w-full xs:text-sm text-xs text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none focus:outline-none focus:ring-0 focus:border-blue-600 peer"
              placeholder=" "
              required
            />
            <label className="peer-focus:font-medium absolute text-sm text-[#234F7E] duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">
              Name
            </label>
          </div>
          <div className="relative z-0 w-full mb-6 group">
            <input
              type="email"
              className="block py-2.5 px-0 w-full xs:text-sm text-xs text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none focus:outline-none focus:ring-0 focus:border-blue-600 peer"
              placeholder=" "
              required
            />
            <label className="peer-focus:font-medium absolute text-sm text-[#234F7E] duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">
              Email address
            </label>
          </div>
          <div className="relative z-0 w-full mb-6 group">
            <input
              type="tel"
              className="block py-2.5 px-0 w-full xs:text-sm text-xs text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none focus:outline-none focus:ring-0 focus:border-blue-600 peer"
              placeholder=" "
              required
            />
            <label className="peer-focus:font-medium absolute text-sm text-[#234F7E] duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">
              Phone number
            </label>
          </div>
          <div className="relative z-0 w-full mb-6 group">
            <textarea
              className="block py-6 px-0 w-full xs:text-sm text-xs text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none focus:outline-none focus:ring-0 focus:border-blue-600 peer"
              placeholder=""
              rows={5}
              required
            />
            <label className="peer-focus:font-medium absolute text-sm text-[#234F7E] duration-300 transform -translate-y-1 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">
              Message
            </label>
          </div>
          <button
            type="submit"
            className="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto sm:px-5 sm:py-2.5 px-3 py-1.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"
          >
            Send a message
          </button>
        </form>
      </div>
      <Footer />
    </div>
  );
};

export default withAuth(pid);
