// Next.js API route support: https://nextjs.org/docs/api-routes/introduction
export default function handler(req, res) {
  const data = [
    {
      ref_no: "aa_sr_0173",
      date_of_issue: "1/10/19",
      contract_period: 2,
      post_applied: "house maid",
      monthly_salary: 1200,
      name: "hikmah bt hasan mesa",
      nationality: "indonesia",
      religion: "muslim",
      date_of_birth: "10/16/92",
      age: 31,
      place_of_birth: "taliwang",
      martial_status: "married",
      no_of_children: 2,
      education: "praimary high school",
      height: "155 cm",
      weight: "55 kg",
      tel_mobile_no: "unknown",
      arabic: 100,
      english: 0,
      uae: 2,
      saudi_arabia: 0,
      kuwait: 0,
      jordan: 0,
      qatar: 0,
      cooking: "yes",
      cleaning: "yes",
      ironing: "yes",
      baby_sitting: "yes",
      caring_for_the_elderly: "no",
      number: "c3862514",
      date_of_exp: "1/10/24",
      place_of_issue: "sumbawa besar",
      photo: "https://i.ibb.co/nr84BQs/Picture1.jpg",
    },
    {
      ref_no: "aa_zo_055",
      date_of_issue: "9/9/22",
      contract_period: 2,
      post_applied: "house maid",
      monthly_salary: 1200,
      name: "birki teka tekelemariam",
      nationality: "ethiopia",
      religion: "christian",
      date_of_birth: "7/20/87",
      age: 36,
      place_of_birth: "shoa",
      martial_status: "married",
      no_of_children: 1,
      education: "grade 8",
      height: "158 cm",
      weight: "50 kg",
      tel_mobile_no: 971504664093,
      arabic: 86.5,
      english: 0,
      uae: 0,
      saudi_arabia: 0,
      jordan: 0,
      qatar: 0,
      kuwait: 7,
      cooking: "yes",
      cleaning: "yes",
      ironing: "yes",
      baby_sitting: "yes",
      caring_for_the_elderly: "no",
      number: "ep7528177",
      date_of_exp: "9/8/27",
      place_of_issue: "addis ababa",
      photo: "https://i.ibb.co/QHxPg9C/Picture2.jpg",
    },
    {
      ref_no: "aa-selfi-68",
      date_of_issue: "11/16/22",
      contract_period: 2,
      post_applied: "house maid",
      monthly_salary: 1200,
      name: "koyah karsum mungkus",
      nationality: "indonesia",
      religion: "muslim",
      date_of_birth: "9/25/79",
      age: 45,
      place_of_birth: "karawang",
      martial_status: "married",
      no_of_children: 2,
      education: "high scool",
      height: "55 cm",
      weight: "50 kg",
      tel_mobile_no: "0544664003 / 0522860554",
      arabic: 90,
      english: 0,
      uae: 2,
      saudi_arabia: 3,
      kuwait: 0,
      jordan: 0,
      qatar: 0,
      cooking: "yes",
      cleaning: "yes",
      ironing: "yes",
      baby_sitting: "yes",
      caring_for_the_elderly: "no",
      number: "c8739589",
      date_of_exp: "11/16/23",
      place_of_issue: "kbri riyadh",
      photo: "https://i.ibb.co/Sm6SHYH/Picture3.jpg",
    },
    {
      ref_no: "aa-iyomi-15",
      date_of_issue: "10/20/22",
      contract_period: 2,
      post_applied: "house maid",
      monthly_salary: 1300,
      name: "neelakanthi kumari",
      nationality: "sri lanka",
      religion: "christian",
      date_of_birth: "2/11/87",
      age: 35,
      place_of_birth: "rabukkana",
      martial_status: "married",
      no_of_children: 2,
      education: "grade 11",
      height: "5.3 cm",
      weight: "65 kg",
      tel_mobile_no: 566721035,
      arabic: 75,
      english: 50,
      uae: 0,
      saudi_arabia: 3,
      kuwait: 0,
      jordan: 0,
      qatar: 10,
      cooking: "yes",
      cleaning: "yes",
      ironing: "yes",
      baby_sitting: "yes",
      caring_for_the_elderly: "no",
      number: "n10022258",
      date_of_exp: "10/20/32",
      place_of_issue: "rabukkana",
      photo: "https://i.ibb.co/sgjPmHK/Picture4.jpg",
    },
    {
      ref_no: "aa-selfi-69",
      date_of_issue: "2/7/23",
      contract_period: 0,
      post_applied: "house maid",
      monthly_salary: 1200,
      name: "daryanti bt sakwo wata",
      nationality: "indonesia",
      religion: "muslim",
      date_of_birth: "3/12/84",
      age: 38,
      place_of_birth: "karawang",
      martial_status: "married",
      no_of_children: 3,
      education: "high scool",
      height: "55 cm",
      weight: "65 kg",
      tel_mobile_no: "0544664003 / 0522860554",
      arabic: 90,
      english: 0,
      uae: 3,
      saudi_arabia: 3,
      kuwait: 0,
      jordan: 0,
      qatar: 0,
      cooking: "yes",
      cleaning: "yes",
      ironing: "yes",
      baby_sitting: "yes",
      caring_for_the_elderly: "no",
      number: "e2706335",
      date_of_exp: "2/7/33",
      place_of_issue: "jakarta timur",
      photo: "https://i.ibb.co/2dDtJZ0/Picture5.jpg",
    },
    {
      ref_no: "aa_fd_21",
      date_of_issue: "1/17/23",
      contract_period: 0,
      post_applied: "house maid",
      monthly_salary: 1000,
      name: "nassaka barbra",
      nationality: "uganda",
      religion: "christian",
      date_of_birth: "9/29/96",
      age: 27,
      place_of_birth: "rakai",
      martial_status: "single",
      no_of_children: 0,
      education: "college/nursery teacher",
      tel_mobile_no: 971544664007,
      arabic: 20,
      english: 100,
      uae: 0,
      saudi_arabia: 0,
      kuwait: 0,
      jordan: 0,
      qatar: 0,
      cooking: "no",
      cleaning: "yes",
      ironing: "yes",
      baby_sitting: "yes",
      caring_for_the_elderly: "no",
      number: "a01005442",
      date_of_exp: "1/16/23",
      place_of_issue: "kampala",
      photo: "https://i.ibb.co/VgcFXjS/Picture6.jpg",
    },
    {
      ref_no: "aa_sr_0176",
      date_of_issue: "1/24/25",
      contract_period: 2,
      post_applied: "house maid",
      monthly_salary: 1200,
      name: "lisda bt sukanta madna",
      nationality: "indonesia",
      religion: "muslim",
      date_of_birth: "1/5/79",
      age: 44,
      place_of_birth: "sukabumi",
      martial_status: "married",
      no_of_children: 2,
      education: "praimary high school",
      height: "158 cm",
      weight: "55 kg",
      tel_mobile_no: "unknown",
      arabic: 100,
      english: 0,
      uae: 4,
      saudi_arabia: 0,
      kuwait: 0,
      jordan: 0,
      qatar: 0,
      cooking: "yes",
      cleaning: "yes",
      ironing: "yes",
      baby_sitting: "yes",
      caring_for_the_elderly: "no",
      number: "c6133991",
      date_of_exp: "1/24/25",
      place_of_issue: "depok",
      photo: "https://i.ibb.co/TPpjrRm/Picture7.jpg",
    },
    {
      ref_no: "aa_zo_057",
      date_of_issue: "2/5/23",
      contract_period: 2,
      post_applied: "house maid",
      monthly_salary: 1200,
      name: "sichale teshome wakoya",
      nationality: "ethiopia",
      religion: "christian",
      date_of_birth: "9/11/93",
      age: 29,
      place_of_birth: "mote",
      martial_status: "single",
      no_of_children: 0,
      education: "high school",
      height: "160 cm",
      weight: "52 kg",
      tel_mobile_no: "unknown",
      arabic: 92,
      english: 0,
      uae: 0,
      saudi_arabia: 0,
      kuwait: 0,
      jordan: 4,
      qatar: 0,
      cooking: "yes",
      cleaning: "yes",
      ironing: "yes",
      baby_sitting: "yes",
      caring_for_the_elderly: "no",
      number: "ep7679640",
      date_of_exp: "2/4/26",
      place_of_issue: "addis ababa",
      photo: "https://i.ibb.co/H4ZcfY1/Picture8.jpg",
    },
    {
      ref_no: "aa_fd_23",
      date_of_issue: "9/21/22",
      contract_period: 2,
      post_applied: "house maid",
      monthly_salary: 1200,
      name: "namulondo zaharah",
      nationality: "uganda",
      religion: "muslim",
      date_of_birth: "8/8/94",
      age: "28 year's",
      place_of_birth: "wakiso",
      martial_status: "single",
      no_of_children: 2,
      education: "high school",
      tel_mobile_no: 971545000000,
      arabic: 20,
      english: 100,
      uae: 2,
      saudi_arabia: 2,
      kuwait: 0,
      jordan: 0,
      qatar: 0,
      cooking: "yes",
      cleaning: "yes",
      ironing: "yes",
      baby_sitting: "yes",
      caring_for_the_elderly: "no",
      number: "a00842832",
      date_of_exp: "9/20/32",
      place_of_issue: "kampala",
      photo: "https://i.ibb.co/Nt1vNNb/Picture9.jpg",
    },
  ];

  if (req.method === "GET") {
    return res.status(200).json({ data: data });
  } else {
    return res.status(404).json({ data: "Not Found" });
  }
}
