/* eslint-disable react-hooks/rules-of-hooks */
import React from "react";
import Banner from "../components/Banner";
import about from "../public/about.jpeg";
import { useTranslation } from "react-i18next";
import Footer from "../components/Footer";
import Head from "next/head";
import withAuth from "../auth/withAuth";

const aboutUs = () => {
  return (
    <div>
      <Head>
        <title>About Us / Tadbeer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icon.ico" />
      </Head>
      <Banner
        imageSrc={about}
        imageUlt="about us banner"
        text1={"About Us"}
        textPosition={
          "top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2"
        }
      />
      <div className="h-full md:mb-44 mb-16 lg:max-w-6xl md:max-w-4xl max-w-sm mx-auto md:space-y-20 space-y-10">
        <div className="space-y-5 xl:mt-28 md:mt-20 mt-5">
          <h1 className="text-[10px] md:text-xl font-roboto font-bold text-[#234F7E]">
            Tadbeer centers are responsible for providing recruitment and
            employment services for domestic workers. These centers which are
            spread throughout the country serves nationals, residents of United
            Arab Emirates and families under the supervision of Ministry of
            Human Resources and Emiratization to achieve the convenience of
            customers.
          </h1>
          <div className="space-y-1">
            <h1 className="text-[10px] md:text-lg font-roboto font-semibold">
              These services include:
            </h1>
            <div className="text-[10px] md:text-base font-roboto font-semibold ml-2">
              <p>
                - Services related to the domestic workers sector provided at
                the Centre.
              </p>
              <p>
                - Providing domestic workers according to the requirements of
                the employer and within the packages available at the center.
              </p>
            </div>
          </div>
          <div className="space-y-1">
            <h1 className="text-[10px] md:text-lg font-roboto font-bold">
              Al Nujoom Domestic workers is partnership organization among four
              UAE nationals. It’s a joint mission between four of the old
              Domestic Workers Offices which had between 20 and 30 plus years of
              experience at the field.
            </h1>
            <h1 className="text-[10px] md:text-base font-roboto font-semibold">
              Old offices where under business names of:
            </h1>
            <div className="text-[10px] md:text-base font-roboto font-semibold ml-2 text-[#234F7E]">
              <p>- Smart Service office</p>
              <p>- Lulu General Service</p>
              <p>- Al Abad Manpower Supply</p>
              <p>- East Service office</p>
            </div>
          </div>
          <div className="space-y-3">
            <h1 className="text-[10px] md:text-lg font-roboto font-bold">
              The offices decided to Join this mission to gather to overcome
              today{"'"}s global challenges on Domestic workers and to ensure
              provides excellent services to our community and customers in
              alignment to UAE labor law and Ministry of Human Recourses and
              Emiratization guidelines.
            </h1>
            <div>
              <h1 className="text-[10px] md:text-base font-roboto font-semibold">
                Our Values are:
              </h1>
              <div className="text-[10px] md:text-base font-roboto font-semibold ml-2 text-[#234F7E]">
                <p>- Quality</p>
                <p>- Excellent Service Delivery</p>
                <p>- Innovation</p>
                <p>- Respect</p>
                <p>- Efficiency</p>
                <p>- Continuous Improvements</p>
              </div>
            </div>
          </div>
          <div className="space-y-3">
            <h1 className="text-[10px] md:text-lg font-roboto font-bold">
              We are looking forward to participating in providing safe and
              excellent service to our community, customers, and Domestic
              workers within our two service lines
            </h1>
            <div>
              <div className="text-[10px] md:text-base font-roboto font-semibold ml-2 text-[#234F7E]">
                <p>
                  1. Providing Domestic workers in three different packages
                  “Traditional, Flexible and temporarily”
                </p>
                <p>2. Transactional and typing Services.</p>
              </div>
            </div>
          </div>
        </div>
      </div>
      <Footer />
    </div>
  );
};

export default withAuth(aboutUs);
