/* eslint-disable react-hooks/rules-of-hooks */
import React, { useState } from "react";
import Banner from "../components/Banner";
import contact from "../public/contact.jpeg";
import { useTranslation } from "react-i18next";
import Footer from "../components/Footer";
import Head from "next/head";
import Map, { Marker } from "react-map-gl";

const contactUs = () => {
  return (
    <div>
      <Head>
        <title>Contact Us / Tadbeer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icon.ico" />
      </Head>
      <Banner
        imageSrc={contact}
        imageUlt="Contact us banner"
        text1={"Contact Us"}
        textPosition={
          "top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2"
        }
      />
      <div className="grid grid-cols-2 bg-[#E7EDF3] md:mb-32 mb-10">
        <div>
          <Map
            mapStyle="mapbox://styles/mapbox/streets-v12"
            mapboxAccessToken="pk.eyJ1Ijoia2FyaW1raGFsZWRlbG1hd2UiLCJhIjoiY2wxa3l4bDRjMDN6ZDNjb2JnbWpzbGVncSJ9.Hr7IeGn4060vCiHaeJH1Zw"
            initialViewState={{
              longitude: 55.51717438199587,
              latitude: 25.256243436006198,
              zoom: 12,
            }}
          >
            <Marker
              longitude={55.51717438199587}
              latitude={25.256243436006198}
              anchor="right"
              color="#FF0000"
              style={{
                cursor: "pointer",
              }}
            ></Marker>
          </Map>
        </div>
        <div className="m-10 space-y-10 max-w-xl mx-auto">
          <h1 className="text-[#E48100] font-lato font-extrabold md:text-4xl md:w-[600px] text-2xl">
            Connect with us
          </h1>
          <div className="flex space-x-16">
            <div className="">
              <h2 className="text-xl font-roboto text-[#234F7E]">Location</h2>
              <p className="text-base ">Agriculture Building,</p>
              <p className="text-base "> Stores land, Maliha Road,</p>
              <p className="text-base ">Sharjah, UAE.</p>
            </div>
            <div className="space-y-4">
              <div>
                <h2 className="text-xl font-roboto text-[#234F7E]">
                  Call Center
                </h2>
                <p className="text-base ">06-767-4222 / 054-995-3973</p>
              </div>
              <div>
                <h2 className="text-xl font-roboto text-[#234F7E]">Email</h2>
                <p className="text-base ">tadbeer.alnujoom@gmail.com</p>
              </div>
            </div>
          </div>
          <div className="bg-[#E7EDF3] py-5 ">
            <form action="" method="post" className="space-y-5">
              <div className="relative z-0 w-full mb-6 group">
                <input
                  type="text"
                  className="block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none focus:outline-none focus:ring-0 focus:border-blue-600 peer"
                  placeholder=" "
                  required
                />
                <label className="peer-focus:font-medium absolute text-sm text-[#234F7E] duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">
                  Name
                </label>
              </div>
              <div className="relative z-0 w-full mb-6 group">
                <input
                  type="email"
                  className="block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none focus:outline-none focus:ring-0 focus:border-blue-600 peer"
                  placeholder=" "
                  required
                />
                <label className="peer-focus:font-medium absolute text-sm text-[#234F7E] duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">
                  Email address
                </label>
              </div>
              <div className="relative z-0 w-full mb-6 group">
                <input
                  type="tel"
                  className="block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none focus:outline-none focus:ring-0 focus:border-blue-600 peer"
                  placeholder=" "
                  required
                />
                <label className="peer-focus:font-medium absolute text-sm text-[#234F7E] duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">
                  Phone number
                </label>
              </div>
              <div className="relative z-0 w-full mb-6 group">
                <textarea
                  className="block py-6 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none focus:outline-none focus:ring-0 focus:border-blue-600 peer"
                  placeholder=""
                  rows={3}
                  required
                />
                <label className="peer-focus:font-medium absolute text-sm text-[#234F7E] duration-300 transform -translate-y-1 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">
                  Message
                </label>
              </div>
              <button
                type="submit"
                className="text-white bg-[#234F7E] clickButton focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center"
              >
                Send Message
              </button>
            </form>
          </div>
        </div>
      </div>
      <Footer />
    </div>
  );
};

export default contactUs;
