/* eslint-disable react-hooks/rules-of-hooks */
import React, { useState } from "react";
import Banner from "../components/Banner";
import Maids from "../components/Maids";
import favourit from "../public/favourit.jpeg";
import maidPhoto from "../public/maidPhoto.png";
import { useTranslation } from "react-i18next";
import Footer from "../components/Footer";
import Head from "next/head";
import withAuth from "../auth/withAuth";
import { useUser } from "../auth/useUser";
import { useQuery } from "@tanstack/react-query";
import { getMaids } from "../fetching/getMaids";

const favourites = () => {
  const { user, logout } = useUser();

  const { t } = useTranslation();

  const { data } = useQuery(["getMaids"], getMaids, {
    staleTime: Infinity,
  });
  console.log(data);
  const [nationality, setNationality] = useState("all");
  const [experience, setExperience] = useState("all");
  const [countryStatus, setCountryStatus] = useState("all");
  return (
    <div>
      <Head>
        <title>Favourites / Tadbeer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icon.ico" />
      </Head>
      <Banner
        imageSrc={favourit}
        imageUlt="favourit banner"
        text1={t("favourite")}
        textPosition={
          "top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2"
        }
      />
      <div className="lg:max-w-6xl md:max-w-2xl mx-auto md:space-y-20 sm:space-y-8 space-y-5 md:mb-44 mb-16">
        <div className="text-center xl:mt-36 md:mt-20 mt-10 space-y-2">
          <h1 className="text-[#E48100] font-lato font-bold md:text-5xl text-2xl">
            {t("favouriteTitle")}
          </h1>
          <p className="md:w-[500px] sm:w-[300px] w-[250px] md:text-sm sm:text-xs text-[10px] mx-auto">
            Lorem ipsum dolor sit amet, ut sed velit euismod vulputate, cum
            nostrud oratio aperiri legimus eu.
          </p>
        </div>
        <Maids
          data={data}
          nationalityFilter={nationality}
          experience={experience}
          countryStatus={countryStatus}
        />
      </div>
      <Footer />
    </div>
  );
};

export default withAuth(favourites);

// viewProfile={t("maidViewProfile")}
//             viewProfileColor={"bg-[#E48100]"}
