/* eslint-disable react-hooks/rules-of-hooks */
import Head from "next/head";
import Banner from "../components/Banner";
import Maids from "../components/Maids";
import findMaid from "../public/findMaids.jpeg";
import maidPhoto from "../public/maidPhoto.png";
import { useTranslation } from "react-i18next";
import Footer from "../components/Footer";
import SearchMaids from "../components/SearchMaids";
import withAuth from "../auth/withAuth";
import axios from "axios";

const findMaids = ({ data }) => {
  const { t } = useTranslation();

  return (
    <div>
      <Head>
        <title>Find Maids / Tadbeer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icon.ico" />
      </Head>
      <Banner
        imageSrc={findMaid}
        imageUlt="find Maids banner"
        text1={t("findMaid")}
        textPosition={
          "top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2"
        }
      />
      <div className="lg:max-w-6xl md:max-w-2xl mx-auto md:space-y-20 sm:space-y-8 space-y-5 md:mb-44 mb-16">
        <div className="text-center xl:mt-36 md:mt-20 mt-10 space-y-2">
          <h1 className="text-[#E48100] font-lato font-bold lg:text-5xl md:text-3xl text-xl">
            {t("findMaidTitle")}
          </h1>
          <p className="md:w-[500px] sm:w-[300px] w-[250px] md:text-sm sm:text-xs text-[10px] mx-auto">
            Lorem ipsum dolor sit amet, ut sed velit euismod vulputate, cum
            nostrud oratio aperiri legimus eu.
          </p>
        </div>
        <SearchMaids />
        <Maids data={data} />
      </div>
      <Footer />
    </div>
  );
};

export default withAuth(findMaids);

export async function getStaticProps(context) {
  const options = {
    method: "GET",
    url: "https://alnujoomerp.net/api/v1/Maids",
    params: { "api-key": "8o0884ws88kkoc484k4s8kg0o04okockk0k0gwso" },
  };

  const res = await axios.request(options);
  return {
    props: {
      data: res.data.response,
    },
  };
}
