/* eslint-disable react-hooks/rules-of-hooks */
import React from "react";
import Head from "next/head";
import Image from "next/image";
import Banner from "../components/Banner";
import ourService from "../public/ourServices.jpeg";
import thumbnail from "../public/video.png";
import play from "../public/playButton.png";
import Footer from "../components/Footer";
const requestService = () => {
  return (
    <div>
      <Head>
        <title>Request service / Tadbeer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icon.ico" />
      </Head>
      <Banner
        imageSrc={ourService}
        imageUlt="Our Services banner"
        text1={"Service Name"}
        textPosition={
          "top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2"
        }
      />
      <div className="grid grid-cols-2 md:mt-2 mt-1 md:ml-2">
        <div className="flex flex-col lg:justify-center lg:items-center md:space-y-5 space-y-2">
          <h1 className="lg:text-4xl md:text-2xl xs:text-sm text-[10px] text-[#E48100] font-lato font-extrabold">
            We are Skillful & Professional
          </h1>
          <p className="lg:w-[521px] lg:ml-10 md:text-base xs:text-[10px] text-[7px]">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
            eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem
            ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
            tempor incididunt ut labore et dolore magna aliqua.
          </p>
          <div className="space-y-2">
            <h3 className="md:text-base xs:text-[10px] text-[7px]">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit:
            </h3>
            <div className="ml-5 space-y-3">
              <h3 className="text-blue-500 md:text-sm xs:text-[8px] text-[5px]">
                🔵 Lorem ipsum dolor sit amet, consectetur adipiscing elit
              </h3>
              <h3 className="text-blue-500 md:text-sm xs:text-[8px] text-[5px]">
                🔵 Lorem ipsum dolor sit amet, consectetur adipiscing elit
              </h3>
              <h3 className="text-blue-500 md:text-sm xs:text-[8px] text-[5px]">
                🔵 Lorem ipsum dolor sit amet, consectetur adipiscing elit
              </h3>
            </div>
          </div>
        </div>
        <div className="relative cursor-pointer md:my-20 my-10 h-fit">
          <div className="xl:w-[500px] md:w-[350px] xs:w-[200px] w-[150px] mx-auto">
            <Image
              src={thumbnail}
              alt="Thumbnail"
              width={800}
              height={450}
              className="rounded-xl"
            />
          </div>
          <div className="md:w-[70px] xs:w-10 w-6 absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 hover:scale-105 transition duration-100 ease-out">
            <Image src={play} alt="play" width={90} height={90} className="" />
          </div>
        </div>
      </div>
      <div className="xl:max-w-7xl lg:max-w-4xl md:max-w-2xl xs:max-w-sm max-w-[280px] mt-1 mx-auto space-y-5 ">
        <p className="xl:text-base lg:text-sm xs:text-[10px] text-[7px]">
          Lorem ipsum dolor sit amet. Aut internos temporibusAut quas vel
          eveniet repellendus 33 impedit sunt? Sit voluptatem reiciendisCum
          galisum in vitae saepe ut distinctio dolore. Ad aspernatur impedit in
          explicabo ducimusEa quis ut nihil magni aut repudiandae error rem
          rerum magnam qui dolor nostrum. Eos dicta dolores et veritatis
          praesentiumQui libero eos internos blanditiis et inventore quidem aut
          architecto autem. Et iure quisquam ea rerum aliasut dolorem ut
          excepturi facilis ad officiis galisum? Qui expedita teneturIn animi
          sit possimus galisum qui minima deleniti! Et iste voluptasAd
          blanditiis a voluptate omnis qui velit quibusdam et voluptas odio. Ut
          ipsum labore et repudiandae praesentiumHic dolorem vel aliquid amet ut
          neque debitis. Ea quod laborum ut vero omniset facilis nam alias
          dolorem. Sed quasi numquam Sed natus aut distinctio ratione? 33
          corporis sapienteSed optio ad repellat nihil 33 iusto dolorem. Sit
          error laboreEt magnam ut deserunt eligendi et voluptatum ratione cum
          totam itaque. Et ratione consectetur et enim consequaturEt corporis
          non earum quasi et expedita similique ut nobis nihil ut fugiat fuga!
          Est iure accusantiumAut iusto ut libero vero ex dolore dolorem.
        </p>
        <p className="xl:text-base lg:text-sm xs:text-[10px] text-[7px]">
          Eos officiis perspiciatisnon officiis est similique facilis? Aut
          voluptas quis ut voluptatibus quiaUt consequuntur rem tempore beatae
          et velit optio hic nihil voluptatibus et ratione aperiam. Aut dolores
          magniEt autem sit dolores quod et minima sequi est libero numquam et
          enim quia. Sed deleniti quiaEst aliquid ea omnis animi est dolorem
          inventore est sint omnis. Et voluptatem suntCum deleniti ea maiores
          cumque aut illo optio sit quis impedit. Est consequatur nulla vel
          nihil quibusdamIn galisum. A explicabo magnam In sint eos possimus
          nulla et dolor voluptas quo fugit laudantium sit internos minima? Ab
          deleniti consequaturEa ipsam est consectetur tempore qui Quis nostrum
          qui amet deserunt sit odit fuga et eveniet beatae. Qui illo impedit
          hic dolore distinctioAut nostrum. Rem distinctio consequuntur ut
          accusamus facilisvel fuga non accusantium temporibus 33 quibusdam
          ipsam? Aut sunt voluptates Sit quidem qui eaque tempora aut
          praesentium expedita? Vel optio eaqueEt corrupti rem nihil tempora ut
          quaerat dolore quo deserunt exercitationem aut laudantium saepe! Sed
          atque porroId voluptatem aut ipsum nihil qui facilis facilis ut ipsa
          expedita. Ea labore delectusQui deleniti a internos consectetur ea
          consectetur et enim consequaturEt corporis non earum quasi et expedita
          similique ut nobis nihil ut fugiat fuga! Est iure accusantiumAut iusto
          ut libero vero ex dolore dolorem. Eos officiis perspiciatisnon
          officiis est similique facilis? Aut voluptas quis ut voluptatibus
          quiaUt consequuntur rem tempore beatae et velit optio hic nihil
          voluptatibus et ratione aperiam. Aut dolores magniEt autem sit dolores
          quod et minima sequi est libero numquam et enim quia. Sed deleniti
          quiaEst aliquid ea omnis animi est dolorem inventore est sint omnis.
          Et voluptatem suntCum deleniti ea maiores cumque aut illo optio sit
          quis impedit. Est consequatur nulla vel nihil quibusdamIn galisum.
        </p>
        <p className="xl:text-base lg:text-sm xs:text-[10px] text-[7px]">
          A explicabo magnam In sint eos possimus nulla et dolor voluptas quo
          fugit laudantium sit internos minima? Ab deleniti consequaturEa ipsam
          est consectetur tempore qui Quis nostrum qui amet deserunt sit odit
          fuga et eveniet beatae. Qui illo impedit hic dolore distinctioAut
          nostrum. Rem distinctio consequuntur ut accusamus facilisvel fuga non
          accusantium temporibus 33 quibusdam ipsam? Aut sunt voluptates Sit
          quidem qui eaque tempora aut praesentium expedita? Vel optio eaqueEt
          corrupti rem nihil tempora ut quaerat dolore quo deserunt
          exercitationem aut laudantium saepe! Sed atque porroId voluptatem aut
          ipsum nihil qui facilis facilis ut ipsa expedita. Ea labore
          delectusQui deleniti a internos consectetur ea assumenda dolore. Aut
          autem voluptates aut itaque nobiseum dolores cum maxime voluptatum.
          Sit autem odio Ea reiciendis non facere eaque ut unde libero. Vel
          dolorum numquamEa atque et galisum enim sed enim repudiandae. Cum
          veritatis quidem qui quod quia Ut laboriosam aut perspiciatis enim est
          quas omnis quo dolores culpa. Ea molestiae similique eos expedita
          distinctioSed officiis ut officiis eius id facere dicta. Aut odit
          inciduntQuo dolore ex omnis dolorem. Et galisum earumRem harum aut
          adipisci quaerat non minima delectus qui adipisci accusamus 33 dolorum
          consequatur. Est impedit veniam33 quia non quos sunt sed voluptatum
          odio ex repellat ullam ut corporis distinctio. Ea expedita perferendis
          non omnis facilis et pariatur omnis. In odio voluptatum vel deleniti
          commodi aut architecto nostrum et quam odit.
        </p>
        <p className="xl:text-base lg:text-sm xs:text-[10px] text-[7px]">
          Aut autem voluptates aut itaque nobiseum dolores cum maxime
          voluptatum. Sit autem odio Ea reiciendis non facere eaque ut unde
          libero. Vel dolorum numquamEa atque et galisum enim sed enim
          repudiandae. Cum veritatis quidem qui quod quia Ut laboriosam aut
          perspiciatis enim est quas omnis quo dolores culpa. Ea molestiae
          similique eos expedita distinctioSed officiis ut officiis eius id
          facere dicta. Aut odit inciduntQuo dolore ex omnis dolorem. Et galisum
          earumRem harum aut adipisci quaerat non minima delectus qui adipisci
          accusamus 33 dolorum consequatur.
        </p>
        <div className="space-y-1">
          <h1 className="xl:text-base lg:text-sm xs:text-[10px] text-[7px]">
            {" "}
            Est enim quia eum sint quam et officiis iure aut fuga facere. Aut
            saepe nobis qui facilis laboriosam ea odit odio a temporibus dolore.
          </h1>
          <div className="ml-5 space-y-2">
            <h1 className="xl:text-base lg:text-sm xs:text-[10px] text-[7px]">
              1- Est enim quia eum sint quam et officiis iure aut fuga facere.
              Aut saepe nobis qui facilis laboriosam ea odit odio a temporibus
              dolore.
            </h1>
            <h1 className="xl:text-base lg:text-sm xs:text-[10px] text-[7px]">
              2- Est enim quia eum sint quam et officiis iure aut fuga facere.
              Aut saepe nobis qui facilis laboriosam ea odit odio a temporibus
              dolore.
            </h1>
            <h1 className="xl:text-base lg:text-sm xs:text-[10px] text-[7px]">
              3- Est enim quia eum sint quam et officiis iure aut fuga facere.
              Aut saepe nobis qui facilis laboriosam ea odit odio a temporibus
              dolore.
            </h1>
            <h1 className="xl:text-base lg:text-sm xs:text-[10px] text-[7px]">
              4- Est enim quia eum sint quam et officiis iure aut fuga facere.
              Aut saepe nobis qui facilis laboriosam ea odit odio a temporibus
              dolore.
            </h1>
          </div>
        </div>
      </div>
      <div className="md:my-22 my-10 bg-[#E7EDF3] md:p-20 p-10">
        <form action="" method="post" className="max-w-xl mx-auto space-y-5">
          <h1 className="block md:text-4xl xs:text-xl text-sm text-center font-medium text-[#234F7E]">
            Service Request Form
          </h1>
          <div className="flex flex-col items-start space-y-3">
            <label className="text-[#234F7E] xs:text-lg text-sm">Service</label>
            <select className="bg-gray-50 border border-gray-300 text-gray-900 xs:text-sm text-[10px] w-60 rounded-lg focus:outline-none block p-2.5">
              <option className="text-[#234F7E] xs:text-base text-sm">
                service 01
              </option>
              <option className="text-[#234F7E] xs:text-base text-sm">
                service 02
              </option>
              <option className="text-[#234F7E] xs:text-base text-sm">
                service 03
              </option>
              <option className="text-[#234F7E] xs:text-base text-sm">
                service 04
              </option>
            </select>
          </div>
          <div className="relative z-0 w-full mb-6 group">
            <input
              type="text"
              className="block py-2.5 px-0 w-full xs:text-sm text-xs text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none focus:outline-none focus:ring-0 focus:border-blue-600 peer"
              placeholder=" "
              required
            />
            <label className="peer-focus:font-medium absolute text-sm text-[#234F7E] duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">
              Name
            </label>
          </div>
          <div className="relative z-0 w-full mb-6 group">
            <input
              type="email"
              className="block py-2.5 px-0 w-full xs:text-sm text-xs text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none focus:outline-none focus:ring-0 focus:border-blue-600 peer"
              placeholder=" "
              required
            />
            <label className="peer-focus:font-medium absolute text-sm text-[#234F7E] duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">
              Email address
            </label>
          </div>
          <div className="relative z-0 w-full mb-6 group">
            <input
              type="tel"
              className="block py-2.5 px-0 w-full xs:text-sm text-xs text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none focus:outline-none focus:ring-0 focus:border-blue-600 peer"
              placeholder=" "
              required
            />
            <label className="peer-focus:font-medium absolute text-sm text-[#234F7E] duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">
              Phone number
            </label>
          </div>
          <div className="relative z-0 w-full mb-6 group">
            <textarea
              className="block py-6 px-0 w-full xs:text-sm text-xs text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none focus:outline-none focus:ring-0 focus:border-blue-600 peer"
              placeholder=""
              rows={5}
              required
            />
            <label className="peer-focus:font-medium absolute text-sm text-[#234F7E] duration-300 transform -translate-y-1 scale-75 top-3 -z-10 origin-[0] peer-focus:left-0 peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">
              Message
            </label>
          </div>
          <button
            type="submit"
            className="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto sm:px-5 sm:py-2.5 px-3 py-1.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"
          >
            Send a message
          </button>
        </form>
      </div>
      <Footer />
    </div>
  );
};

export default requestService;
