import Head from "next/head";
import React from "react";
import Footer from "../components/Footer";
import Header from "../components/Header";
import Signin from "../components/Signin";

const signin = () => {
  return (
    <div>
      <Head>
        <title>Sign in / Tadbeer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icon.ico" />
      </Head>
      <Signin />
      <Footer />
    </div>
  );
};

export default signin;
