import Head from "next/head";
import Image from "next/image";
import React from "react";
import Header from "../components/Header";
import paymentSuccess from "../public/paymentSuccess.png";
const success = () => {
  return (
    <div>
      <Head>
        <title>Payment success / Tadbeer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icon.ico" />
      </Head>
      <Header />
      <div className="grid grid-cols-2 pt-36">
        <div className="flex flex-col justify-center items-center">
          <h1 className="text-5xl font-lato font-bold text-gray-600">
            Payment successful
          </h1>
          <p className="text-lg font-roboto font-semibold">
            Thank you for choosing{" "}
            <span className="underline decoration-yellow-500 text-blue-500">
              Tadbeer Alnujoom
            </span>{" "}
            we will reach you soon
          </p>
        </div>
        <div>
          <Image src={paymentSuccess} alt="payment success" />
        </div>
      </div>
    </div>
  );
};

export default success;
