/* eslint-disable react-hooks/rules-of-hooks */
import React, { useEffect, useState } from "react";
import Banner from "../components/Banner";
import upcomingInterview from "../public/upcomingInterviews.jpeg";
import { useTranslation } from "react-i18next";
import Footer from "../components/Footer";
import Head from "next/head";
import withAuth from "../auth/withAuth";
import { useUser } from "../auth/useUser";
import { collection, query } from "firebase/firestore";
import { db } from "../config";
import { useCollection } from "react-firebase-hooks/firestore";
import MaidFire from "../components/MaidFire";

const upcomingInterviews = () => {
  const { user, logout } = useUser();
  const { t } = useTranslation();
  const [snapshot] = useCollection(
    query(
      collection(
        db,
        "users",
        user?.email || "karimkhaledelmawe.gmail.com",
        "upcomingInterviews"
      )
    )
  );

  return (
    <div>
      <Head>
        <title>Interviews / Tadbeer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icon.ico" />
      </Head>
      <Banner
        imageSrc={upcomingInterview}
        imageUlt="upcoming Interviews banner"
        text1={t("upcoming")}
        textPosition={
          "top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2"
        }
      />
      <div className="lg:max-w-6xl md:max-w-2xl mx-auto md:space-y-20 sm:space-y-8 space-y-5 md:mb-44 mb-16">
        <div className="text-center xl:mt-36 md:mt-20 mt-10 space-y-2">
          <h1 className="text-[#E48100] font-lato font-bold md:text-5xl text-2xl">
            {t("upcomingTitle")}
          </h1>
          <p className="md:w-[500px] sm:w-[300px] w-[250px] md:text-sm sm:text-xs text-[10px] mx-auto">
            Lorem ipsum dolor sit amet, ut sed velit euismod vulputate, cum
            nostrud oratio aperiri legimus eu.
          </p>
        </div>
        <div className="grid lg:grid-cols-5 grid-cols-3 xl:gap-x-10 lg:gap-x-2 md:gap-y-28 gap-y-10 pt-5">
          {user?.email &&
            snapshot?.docs.map((maid) => (
              <MaidFire key={maid.id} id={maid.id} />
            ))}
        </div>
      </div>
      <Footer />
    </div>
  );
};

export default withAuth(upcomingInterviews);

// up={"Upcoming"}
// live={"Live"}
// history={"History"}
// upColor={"bg-[#F9B730]"}
// liveColor={"bg-[#68B34A]"}
// historyColor={"bg-[#EE2424]"}
